# Generated by Django 6.0.1 on 2026-02-21 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('hod', 'HOD'), ('staff', 'Office Staff')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('bsc_cs', 'B.Sc. Computer Science'), ('bsc_micro', 'B.Sc. Microbiology'), ('bsc_biochem', 'B.Sc. Biochemistry'), ('bsc_biotech', 'B.Sc. Biotechnology'), ('bsc_psy', 'B.Sc Psychology'), ('bsc_food', 'B.Sc. Food Technology'), ('bcom_ca', 'B.Com with Computer Application'), ('bcom_fin', 'B.Com Finance'), ('bcom_mark', 'B.Com Marketing'), ('bcom_coop', 'B.Com Co-operation'), ('bba', 'B.B.A.'), ('ba_eng', 'B.A English'), ('ba_eco', 'B.A Economics'), ('msc_cs', 'M.Sc Computer Science'), ('msc_biotech', 'M.Sc Biotechnology'), ('msc_micro', 'M.Sc Microbiology'), ('msc_biochem', 'M.Sc Biochemistry')], max_length=30, null=True)),
                ('admission_no', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('university_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('office', 'Office Notice'), ('department', 'Department Notice')], max_length=20)),
                ('display_category', models.CharField(choices=[('academic', 'Academic Notices'), ('events', 'Events & Programs'), ('department_updates', 'Department Notices'), ('exam', 'Exam Notifications'), ('holiday', 'Holiday Announcements'), ('urgent', 'Urgent Alerts'), ('clubs', 'Clubs & Activities')], max_length=30)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
